#!/usr/bin/env python3
import argparse
import sys

lineno = 0


def print_file(f, show_lineno):
    for line in f:
        if show_lineno:
            global lineno
            lineno += 1
            line = f"{lineno:>6d}\t{line}"
        sys.stdout.write(line)


def main(args):
    files = args.filenames or [sys.stdin]

    show_lineno = args.show_lineno

    for file in files:
        if hasattr(file, "read"):
            # file-like object
            print_file(file, show_lineno)
        elif file == "-":
            # stdin in args
            print_file(sys.stdin, show_lineno)
        else:
            # filename provided
            with open(file) as f:
                print_file(f, show_lineno)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="cat",
        description="Concatenate files",
    )

    parser.add_argument("filenames", nargs="*")
    parser.add_argument(
        "-n",
        "--number",
        action="store_true",
        dest="show_lineno",
        help="print line numbers",
    )
    args = parser.parse_args()
    main(args)
