#!/usr/bin/env python3
import argparse
import sys

parser = argparse.ArgumentParser(
    prog="cat",
    description="Concatenate files",
)

parser.add_argument("filenames", nargs="*")
parser.add_argument(
    "-n", "--number", action="store_true", dest="show_lineno", help="print line numbers"
)
args = parser.parse_args()

files = args.filenames or [sys.stdin]
lineno = 0
show_lineno = args.show_lineno


def print_file(f):
    for line in f:
        if show_lineno:
            global lineno
            lineno += 1
            line = f"{lineno:>6d}\t{line}"
        sys.stdout.write(line)


for file in files:
    if hasattr(file, "read"):
        # file-like object
        print_file(file)
    elif file == "-":
        # stdin in args
        print_file(sys.stdin)
    else:
        # filename provided
        with open(file) as f:
            print_file(f)
