#!/usr/bin/env python3
import argparse
import sys

parser = argparse.ArgumentParser(
    prog='cat',
    description='Concatenate files',
)

parser.add_argument('filenames', nargs="*")
parser.add_argument('-n', action='store_true', dest='show_lineno')
args = parser.parse_args()

files = args.filenames or [sys.stdin]
lineno = 0
show_lineno = args.show_lineno


def print_file(f):
    for line in f:
        if show_lineno:
            global lineno
            lineno += 1
            line = f'{lineno:>6d}\t{line}'
        sys.stdout.write(line)

for file in files:
    try:
        with open(file, 'rt') as f:
            print_file(f)
    except TypeError:
        # could be stdin
        print_file(file)
