#!/usr/bin/env python

import argparse
import pathlib
import stat

DEFAULT_DIRECTORY = "."
DEFAULT_GLOB_PATTERN = "*"

parser = argparse.ArgumentParser(prog="find", description="Find files")

parser.add_argument(
    "directory", nargs="?", help="directory to search", default=DEFAULT_DIRECTORY
)
parser.add_argument(
    "-name",
    dest="glob_pattern",
    action="store",
    help="name pattern to match",
    default=DEFAULT_GLOB_PATTERN,
)
parser.add_argument(
    "-type",
    choices=('d', 'f'),
    help="the file type to match"
)

args = parser.parse_args()

directory = args.directory
glob_pattern = args.glob_pattern

matches = pathlib.Path(directory).rglob(glob_pattern)

is_file_match = args.type == "f"
is_dir_match = args.type == "d"

if is_file_match:
    matches = (p for p in matches if stat.S_ISREG(p.lstat().st_mode))
elif is_dir_match:
    matches = (p for p in matches if stat.S_ISDIR(p.lstat().st_mode))

if glob_pattern == DEFAULT_GLOB_PATTERN and not is_file_match:
    print(directory)  # print starting point

if directory == DEFAULT_DIRECTORY:
    fmt_str = "./{path}"
else:
    fmt_str = "{path}"

for p in matches:
    print(fmt_str.format(path=p))  # default action is -print
