#!/usr/bin/env python

import argparse
import pathlib

DEFAULT_DIRECTORY = "."
DEFAULT_GLOB_PATTERN = "*"

parser = argparse.ArgumentParser(prog="find", description="Find files")

parser.add_argument(
    "directory", nargs="?", help="directory to search", default=DEFAULT_DIRECTORY
)
parser.add_argument(
    "-name",
    dest="glob_pattern",
    action="store",
    help="name pattern to match",
    default=DEFAULT_GLOB_PATTERN,
)

args = parser.parse_args()

directory = args.directory
glob_pattern = args.glob_pattern

matches = pathlib.Path(directory).rglob(glob_pattern)

if glob_pattern == DEFAULT_GLOB_PATTERN:
    print(directory)  # print starting point

if directory == DEFAULT_DIRECTORY:
    fmt_str = "./{path}"
else:
    fmt_str = "{path}"

for p in matches:
    print(fmt_str.format(path=p))  # default action is -print
