#!/usr/bin/env python
import pathlib
import sys
import re
import argparse
import itertools


def filter_lines(lines, pattern, insensitive_match, invert_match):
    for i, l in enumerate(lines):
        re_flags = re.IGNORECASE if insensitive_match else 0
        pattern_found = re.search(pattern, l, re_flags)
        match_found = pattern_found if not invert_match else not pattern_found
        if match_found:
            yield i, l


def format_output(lines, filename=None, show_lineno=False):
    fmt = "{lineno}:{line}" if show_lineno else "{line}"
    fmt = f"{filename}:" + fmt if filename else fmt
    for i, l in lines:
        yield fmt.format(line=l, lineno=i + 1)


def process(args, file, filename=None):
    matching_lines = filter_lines(
        (l for l in file), args.pattern, args.insensitive_match, args.invert_match
    )
    yield from format_output(matching_lines, filename, args.show_lineno)


def output_action(line):
    print(line, end="")


def check_multiple_items(files):
    iterator, sentinel = iter(files), None
    first = next(iterator, sentinel)
    if first is not sentinel:
        second = next(iterator, sentinel)
        if second is not sentinel:
            iterator = itertools.chain([first, second], iterator)
            result = True
        else:
            iterator = itertools.chain([first], iterator)
            result = False
    else:
        result = False
    return result, iterator


def main(args):
    if not args.files:
        files = [pathlib.Path.cwd()] if args.recursive_search else [sys.stdin]
    else:
        files = args.files

    if args.recursive_search:
        # recursively search any directories
        dirs = [p for p in files if p is not sys.stdin and p.is_dir()]
        glob_iterator = itertools.chain.from_iterable([p.rglob("*") for p in dirs])
        files = itertools.chain(files, glob_iterator)

    # check if we have more than one file
    has_multiple, files = check_multiple_items(files)

    for file in files:
        if file is sys.stdin:
            for l in process(args, file):
                output_action(l)
        else:
            if args.recursive_search and file.is_dir():
                continue
            with open(file, "rt") as f:
                show_filenames = has_multiple
                filename = file if show_filenames else None
                for l in process(args, f, filename=filename):
                    output_action(l)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="grep", description="find matching lines")
    parser.add_argument(
        "-i",
        action="store_true",
        dest="insensitive_match",
        help="case insensitive search",
    )
    parser.add_argument(
        "-r",
        action="store_true",
        dest="recursive_search",
        help="recursively search directories",
    )
    parser.add_argument(
        "-n",
        action="store_true",
        dest="show_lineno",
        help="show matching line number",
    )
    parser.add_argument(
        "-v",
        action="store_true",
        dest="invert_match",
        help="show lines that do not match pattern",
    )
    parser.add_argument("pattern", help="pattern to find")
    parser.add_argument("files", nargs="*", help="files to search", type=pathlib.Path)
    args = parser.parse_args()
    main(args)
