#!/usr/bin/env python

import sys
import re
import argparse


def filter_lines(lines, pattern, insensitive_match):
    for l in lines:
        re_flags = re.IGNORECASE if insensitive_match else 0
        if re.search(pattern, l, re_flags):
            yield l


def format_output(lines, filename=None):
    fmt_str = f"{filename}:" + "{line}" if filename else "{line}"
    for l in lines:
        yield fmt_str.format(line=l)


def process(pattern, file, insensitive_match, filename=None):
    matching_lines = filter_lines((l for l in file), pattern, insensitive_match)
    yield from format_output(matching_lines, filename)


def output_action(line):
    print(line, end="")


def main(args):
    files = args.files or [sys.stdin]
    for file in files:
        if file is sys.stdin:
            for l in process(args.pattern, file, args.insensitive_match, filename=None):
                output_action(l)
        else:
            with open(file, "rt") as f:
                show_filenames = len(files) > 1
                filename = file if show_filenames else None
                for l in process(
                    args.pattern, f, args.insensitive_match, filename=filename
                ):
                    output_action(l)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="grep", description="find matching lines")
    parser.add_argument(
        "-i",
        action="store_true",
        dest="insensitive_match",
        help="case insensitive search",
    )
    parser.add_argument("pattern", help="pattern to find")
    parser.add_argument("files", nargs="*", help="files to search")
    args = parser.parse_args()
    main(args)
